### ISSUE TITLE
Datadome

### ISSUE THREAD

**Issue by ukaare** [MoterHaker/bypass-captcha-examples#1]
Hello, its possible to bypass datadome captcha in www.courir.es?

**Comment by MoterHaker** [comment]
Yes sure, there's example already, just replace your URL
https://github.com/MoterHaker/bypass-captcha-examples/blob/main/geo.captcha-delivery.com.js

**Comment by ukaare** [comment]
> Yes sure, there's example already, just replace your URL
> https://github.com/MoterHaker/bypass-captcha-examples/blob/main/geo.captcha-delivery.com.js

but the example dont says datadome
