### ISSUE TITLE
Datadome bypass with AntiGate still not pass

### ISSUE THREAD

**Issue by GCChen** [MoterHaker/bypass-captcha-examples#11]
I get the datadome cookie successfully, but I get 403 when I request url with that datadome cookie.

**Comment by internpoon** [comment]
same ^

**Comment by alvintclam** [comment]
same

**Comment by midosoli** [comment]
Same

**Comment by mamihelj09** [comment]
same

**Comment by MoterHaker** [comment]
Can anyone provide an example url with Datadome protection?

Another question: did you try providing a proxy for Antigate task and using that proxy for further navigation at the protected website?

**Comment by thapld** [comment]
Here website url: https://www.[boxed.com](https://www.boxed.com/login)/login
Get bypass cookie but access 403

**Comment by AdminAnticaptcha** [comment]
Fixed by modifying CSS selector and using cookie from top level domain

**Comment by MoterHaker** [comment]
Fixed, see examples.
