### ISSUE TITLE
Geo.captcha delivery service down error

### ISSUE THREAD

**Issue by alihussain47** [MoterHaker/bypass-captcha-examples#12]
![image](https://user-images.githubusercontent.com/39479087/171115434-a1e099da-7340-4029-9d26-a738bac579e9.png)

Facing Geo.captcha delivery service down, not solving captcha.
Showing captcha service down or moved to new address error.
Screenshot Attached.

**Comment by MoterHaker** [comment]
The screenshot says geo.captcha-delivery.com is down.
Not Anti-Captcha.

What a jerk.
