### ISSUE TITLE
captchaCallback Not Defined

### ISSUE THREAD

**Issue by jstadeusiak** [MoterHaker/bypass-captcha-examples#2]
Hi There, 
I am trying to use the datadome captcha bypass method you have and I am encountering an error.  The error is a puppeteer reference error saying the "captchaCallback is not defined". I did modify the file a small bit so I could export the function and use it in another file. I also changed the captcha sitekey, which I assume is proper as I am attempting to bypass datadome on pokemoncenter.com.

**Comment by MoterHaker** [comment]
What's the full address with captcha?

**Comment by jstadeusiak** [comment]
https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAj5RZnzoB-VEApgGbJw%3D%3D&hash=5B45875B653A484CC79E57036CE9FC&cid=5BQ2~v5-CokJheG3P803g0AxY1n__szvx-W5i-I~~IRnIVW~XCHdoZmZI8gz4ZUksFKQ_9JpbFiOWO4pUNjXuUKHtdGR8eB7CZitdI0K.n&t=bv&referer=https%3A%2F%2Fwww.pokemoncenter.com%2Ftpci-ecommweb-api%2Fproduct%3Fformat%3Dzoom.nodatalinks&s=9817

**Comment by jstadeusiak** [comment]
I see now looking at this there is no captcha even rendered, just a full block. Anyway I can presolve to prevent this.

**Comment by jstadeusiak** [comment]
Or a way to prevent this?

**Comment by MoterHaker** [comment]
Address you gave is blocked permanently. You need to grab new address from pokemoncenter and feed it to the script. When there's no captcha, then there's no way to bypass it.

**Comment by jstadeusiak** [comment]
Okay, so the captcha is there now, and I can see the captchaCallback function in the page's elements, but its still failing to find the function 'captchaCallback'.  Any suggestions?

**Comment by jstadeusiak** [comment]
https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAbFxKeyvQVvcArHWjKw%3D%3D&hash=5B45875B653A484CC79E57036CE9FC&cid=8RgMHiwib9ru9~lDbJ7nN_x4O8Ps10E0G7MJlob1Ifdsxv~PJe8yRipd-Zn6msb2KUNn~chQl3gbodPjmnFcxAWb7967bH0zQgtOq3mqcw&t=fe&referer=https%3A%2F%2Fwww.pokemoncenter.com%2Ftpci-ecommweb-api%2Fsearch%3Fq%3D*%26_br_uid_2%3Duid%253D2838858306653%253Av%253D12.0%253Ats%253D1610326297970%253Ahc%253D5%26ref_url%3D%26rows%3D200%26start%3D0%26url%3Dwww.pokemoncenter.com%26fl%3Dpid%2Ctitle%2Cbrand%2Cprice%2Csale_price%2Cpromotions%2Cthumb_image%2Csku_thumb_images%2Csku_swatch_images%2Csku_color_group%2Curl%2Cprice_range%2Csale_price_range%2Cdescription%2Cbest_seller%2Claunch_date%2Csale_price%2CPRF%2Cdisplay_price%2Cdisplay_sale_price%2Ccurrency%2Creporting_crumb%2Creporting_product_name%2C%26sort%3Dlaunch_date%2Bdesc%26search_type%3Dkeyword%26fq%3Dlaunch_date_epoch%3A%5B1604102400%2520TO%25201611854868%5D&s=9817

Here is an example url, I know datadome can be "turned up" in the sense that it becomes stricter, which right now is when its probably at its highest settings. I dont think that should affect it though.
