### ISSUE TITLE
Amazon Flex

### ISSUE THREAD

**Issue by luizsilva-dev** [MoterHaker/bypass-captcha-examples#25]
I can pass amazon flex captcha using your code. But I am not able to validate the token for the captcha to go away. I think it is missing to send some parameter that informs that that captcha refers to my account.
Any suggestion?

**Comment by MoterHaker** [comment]
You should report both bad and good tokens to Anti-Captcha.

Use these methods:
https://anti-captcha.com/apidoc/methods/reportIncorrectRecaptcha
https://anti-captcha.com/apidoc/methods/reportCorrectRecaptcha

**Comment by luizsilva-dev** [comment]
> You should report both bad and good tokens to Anti-Captcha.
> 
> Use these methods: https://anti-captcha.com/apidoc/methods/reportIncorrectRecaptcha https://anti-captcha.com/apidoc/methods/reportCorrectRecaptcha

But those docs refer to recaptcha. Amazon uses funcaptcha and doesn't have any docs about it.

**Comment by MoterHaker** [comment]
Just. Do. It.
