### ISSUE TITLE
Datadome captcha solved but still pending 

### ISSUE THREAD

**Issue by louissmsfactor** [MoterHaker/bypass-captcha-examples#8]
Hi I use your code to bypass Data dome captcha, everything is good but when it solved, nothing append after this loader.
Do you have any ideas, what's wrong with your code?
![image](https://user-images.githubusercontent.com/48249347/147466841-be192ef4-8b2b-489a-ae40-758003f600e4.png)
Thanks

**Comment by solving-captcha-concepts** [comment]
Check out new update.
